consts:
  U: 90
  Y_step: 2.5
  a: 0.52758
  cluster_importancy: 0.0
  const: 0.25
  down_steps: 3
  max_depth: 10
  percent_X: 5.0
  percent_Y: 33
  percent_for_norms: 40.0
  percent_of_zeros: 0.5
  power_koef: 1.16
  round_const: 5
  threshold: 0.8
  up_steps: 3
  w: 8
conturs:
  contour_points: 50
  min_diff: 0.00029
  min_points: 30
  num_of_lenghts: 4
ignore_coord: []
isolated_cluster:
  constU1: 0.05
  divider: 2
  max_div_num: 8
  merge_threshold: 0.00215
  min_dif: 0.00143
  min_len: 0.26379
knots:
  min_fuses_num: 15
  stop_const: 0.52758
norms:
  X1: 0.12398
  X2: 0.45911
  X3: 63.09714
  X4: 27.65201
  X5: 17.59687
subcluster:
  Max_persent: 90
  Steps: 10
  max_key_points: 5
