consts:
  Y_step: 2.5
  a: 0.41
  const: 0.25
  down_steps: 4
  max_depth: 10
  percent_X: 5.0
  percent_Y: 33.0
  percent_for_norms: 40.0
  percent_of_zeros: 0.005
  power_koef: 1.16
  round_const: 2
  threshold: 0.8
  up_steps: 6
conturs:
  contour_points: 50
  min_diff: 0.01
  min_points: 30
  num_of_lenghts: 4
ignore_coord: []
isolated_cluster:
  constU1: 0.05
  divider: 2
  max_div_num: 8
  merge_threshold: 1.75
  min_dif: 0.01
  min_len: 0.21
knots:
  min_fuses_num: 15
  stop_const: 0.41
norms:
  X1: 0.16
  X2: 0.43
  X3: 31.82
subcluster:
  F_step: 0.001
