consts:
  U: 90
  Y_step: 2.5
  a: 0.6886
  const: 0.25
  down_steps: 3
  max_depth: 10
  percent_X: 5.0
  percent_Y: 33.0
  percent_for_norms: 40.0
  percent_of_zeros: 0.5
  power_koef: 1.16
  round_const: 5
  threshold: 0.8
  up_steps: 3
  w: 8
conturs:
  contour_points: 50
  min_diff: 0.00129
  min_points: 30
  num_of_lenghts: 4
ignore_coord:
- X1
- X2
isolated_cluster:
  constU1: 0.05
  divider: 2
  max_div_num: 8
  merge_threshold: 1.75
  min_dif: 0.00643
  min_len: 0.3443
knots:
  min_fuses_num: 15
  stop_const: 0.6886
norms:
  X1: 28.71407
  X1_original: 0.13688
  X2: 0.45135
  X3: 23.69431
  X3_original: 63.56016
  X4: 0.12804
  X4_original: 24.7794
  X5: 17.1858
subcluster:
  Max_persent: 99
  Steps: 10
  max_key_points: 5
