consts:
  Y_step: 2.5
  const: 0.25
  down_steps: 4
  max_depth: 10
  percent_X: 5.0
  percent_Y: 33.0
  percent_for_norms: 40.0
  percent_of_zeros: 0.005
  power_koef: 1.16
  round_const: 2
  threshold: 0.8
  up_steps: 6
conturs:
  contour_points: 50
  min_diff:
  - 20.0
  - 20.0
  min_points: 30
  num_of_lenghts: 85
ignore_coord:
- X2
isolated_cluster:
  constU1: 0.05
  divider: 2
  max_div_num: 8
  merge_threshold: 1.75
  min_dif:
  - 20.0
  - 20.0
  min_len: 0.5
knots:
  min_fuses_num: 15
  stop_const: 1
subcluster:
  F_step: 0.001
