consts:
  U: 90
  Y_step: 2.5
  a: 0.13773
  const: 0.25
  down_steps: 3
  max_depth: 10
  percent_X: 5
  percent_Y: 33
  percent_for_norms: 40
  percent_of_zeros: 0.5
  power_koef: 1.16
  round_const: 5
  threshold: 0.8
  up_steps: 3
  w: 8
conturs:
  contour_points: 50
  min_diff: 0.01309
  min_points: 30
  num_of_lenghts: 4
isolated_cluster:
  constU1: 0.05
  divider: 2
  max_div_num: 8
  merge_threshold: 1.75
  min_dif: 0.06544
  min_len: 0.06886
knots:
  min_fuses_num: 15
  stop_const: 0.13773
norms:
  X1: 4.23351
  X2: 3.32908
subcluster:
  Max_persent: 90
  Steps: 10
  max_key_points: 5
