consts:
  U: 90
  Y_step: 2.5
  a: 0.50625
  cluster_importancy: 0.5
  const: 0.25
  down_steps: 3
  max_depth: 10
  percent_X: 5.0
  percent_Y: 33
  percent_for_norms: 40
  percent_of_zeros: 0.5
  power_koef: 1.16
  round_const: 5
  threshold: 0.8
  up_steps: 3
  w: 8
conturs:
  contour_points: 50
  min_diff: 0.00329
  min_points: 30
  num_of_lenghts: 4
ignore_coord:
- X1
- X2
- X3
isolated_cluster:
  constU1: 0.05
  divider: 2
  max_div_num: 8
  merge_threshold: 0.02471
  min_dif: 0.01647
  min_len: 0.25312
knots:
  min_fuses_num: 15
  stop_const: 0.50625
norms:
  X1: 0.12606
  X2: 0.49396
  X3: 71.56692
  X4: 34.11526
  X4_original: 35.811
  X5: 15.59433
  X5_original: 19.714
subcluster:
  Max_persent: 90
  Steps: 10
  max_key_points: 5
