consts:
  U: 90
  Y_step: 2.5
  a: 0.06165
  cluster_importancy: 0.5
  const: 0.25
  down_steps: 3
  max_depth: 10
  percent_X: 5
  percent_Y: 33
  percent_for_norms: 40
  percent_of_zeros: 0.5
  power_koef: 1.16
  round_const: 5
  threshold: 0.8
  up_steps: 3
  w: 8
conturs:
  contour_points: 50
  min_diff: 0.01065
  min_points: 30
  num_of_lenghts: 4
isolated_cluster:
  constU1: 0.05
  divider: 2
  max_div_num: 8
  merge_threshold: 0.07987
  min_dif: 0.05324
  min_len: 0.03082
knots:
  min_fuses_num: 15
  stop_const: 0.06165
norms:
  X1: 3.09369
  X1_original: 2.31235
  X2: 1.70604
  X2_original: 3.726
subcluster:
  Max_persent: 90
  Steps: 10
  max_key_points: 5
