consts:
  U: 75.0
  Y_step: 2.5
  a: 0.10647
  const: 0.25
  down_steps: 4
  max_depth: 10
  percent_X: 5.0
  percent_Y: 33.0
  percent_for_norms: 40.0
  percent_of_zeros: 0.005
  power_koef: 1.16
  round_const: 5
  threshold: 0.8
  up_steps: 6
  w: 6.0
conturs:
  contour_points: 50
  min_diff: 0.00727
  min_points: 30
  num_of_lenghts: 4
ignore_coord: []
isolated_cluster:
  constU1: 0.05
  divider: 2
  max_div_num: 8
  merge_threshold: 1.75
  min_dif: 0.03637
  min_len: 0.05323
knots:
  min_fuses_num: 15
  stop_const: 0.10647
norms:
  X1: 3.60856
  X2: 3.95633
subcluster:
  F_step: 0.001
