consts:
  Y_step: 10.0
  a: 10.6
  const: 10.0
  down_steps: 4
  max_depth: 10
  percent_X: 21.0
  percent_Y: 33.0
  percent_for_norms: 40.0
  percent_of_zeros: 0.005
  power_koef: 1.16
  round_const: 2
  threshold: 0.8
  up_steps: 6
conturs:
  contour_points: 50
  min_diff: 0.0
  min_points: 30
  num_of_lenghts: 4
ignore_coord: []
isolated_cluster:
  constU1: 0.05
  divider: 2
  max_div_num: 8
  merge_threshold: 1.75
  min_dif: 0.0
  min_len: 5.3
knots:
  min_fuses_num: 15
  stop_const: 10.6
subcluster:
  F_step: 0.001
