# Generated by Django 3.1.7 on 2021-09-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f_clustering', '0003_auto_20210922_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
